### ISSUE TITLE
my file doesn't work.

### ISSUE THREAD

**Issue by frankzen** [josch/pyferea#1]
Hope you are still around.....downloaded your Zip file...dumped it in my home directory, downloaded and installed necessary dependencies. Runs fine with you example file, but when I created my own...

creating new db at ./pyferea.sqlite
Traceback (most recent call last):
  File "pyferea.py", line 1164, in <module>
    feedreader = FeedReaderWindow()
  File "pyferea.py", line 977, in **init**
    config = yaml.load(f)
  File "/usr/lib/python2.7/dist-packages/yaml/**init**.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 128, in peek_token
    self.fetch_more_tokens()
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "./feeds.yaml", line 2, column 11

This is my feeds.yaml

frank@frank:~/pyferea-master$ cat feeds.yaml
http://www.kijiji.ca/rss-srp-house-for-sale/ontario/victorian/
  category: "Victorian homes"
  loadlink: "True"
http://blog.fefe.de/rss.xml?html:
  category: "general news"
  loadlink: False
http://www.lawblog.de/index.php/feed/:
  category: "general news"
  loadlink: False
http://feeds.feedburner.com/theatlantic/infocus:
  category: "general news"
  loadlink: False
http://feeds.boston.com/boston/bigpicture/index:
  category: "general news"
  loadlink: False
http://neusprech.org/feed/:
  category: "general news"
  loadlink: False
http://planet.debian.org/rss20.xml:
  category: "IT news"
  loadlink: False
http://www.debian-administration.org/atom.xml:
  category: "IT news"
  loadlink: False
http://www.engadget.com/exclude/Apple/rss.xml:
  category: "IT news"
  loadlink: False
http://slashdot.org/slashdot.rss:
  category: "IT news"
  loadlink: True

The first entry is new, the rest is from your example. After checking line 2 col 11 appears to be a space ???

**Comment by josch** [comment]
Sorry, this project is completely abandoned. I moved on to using ttrss.

The problem seems to be your yaml file which is missing a colon after the first line.

**Comment by frankzen** [comment]
Ahh. Thanks. Didn't see it ( cuz it wasn't there :) )

Thanks

Too bad you've abandoned it.
